### ISSUE TITLE
Consider versions for the Prekey server spec

### ISSUE THREAD

**Issue by claucece** [otrv4/otrv4-prekey-server#10]

**Comment by claucece** [comment]
Ok, so I have added a "Prekey Query Retrieval" message: https://github.com/otrv4/otrv4-prekey-server/commit/b97807c3b058a96429eea0769a217ec4083fc535, that includes the versions you want for this participant. 

I think Client and Prekey profiles should have a version as the prekey message, in case they get upgraded in future versions. 

Thoughts? @olabini

**Comment by olabini** [comment]
Well, this is an important addition - but I think my initial comment was about the actual prekey server spec having a version - so that if we ever need to publish a new version of the spec/protocol, it will be possible for clients to say what version of the prekey protocol they're speaking, and the same with the server.

**Comment by claucece** [comment]
Mmm.. so you mean: OTRv5 protocol will have a OTRv5 prekey server, OTRv6 protocol will have a OTRv6 prekey server... et alia, and each version will find its own. Then on OTRv4 prekey server we should not store anything but v4 prekey ensemble values, right?

**Comment by claucece** [comment]
No, wait.. I guess is more advertising the prekey server which version is currently been spoken, rather than having different prekey servers.. right?

**Comment by claucece** [comment]
@olabini please, check ;)

**Comment by olabini** [comment]
Well, what I mean is something in between. It would be annoying to have one server instance for each version. So I think a mechanism where it would be possible for one server to speak several different versions would be useful. And for that to work, the messages need to have some indication of what version they are for as well. Make sense?

**Comment by claucece** [comment]
Ok.. I have included so :)
