### ISSUE TITLE
How would the prekey server functionality work on a "network" that doesn't have any central infrastructure?

### ISSUE THREAD

**Issue by claucece** [otrv4/otrv4-prekey-server#11]
Such as Ricochet.

**Comment by claucece** [comment]
So, after looking at the Ricochet spec, 

```
Each user identity is represented by a hidden service as its connection point. The identity is shared as
a contact ID in the form ricochet:qjj5g7bxwcvs3d7i, which is unique and sufficient to connect to the
service.
```

I guess we can use this same hidden/onion service to represent the prekey server identity, and make the prekey server work as another participant in the connection.  It can be found by the assembled descriptor (requesting XYZ.onion where XYZ is a 16 character name derived from the service's public key).

The difficulty on this is that with Ricochet, for example, each Ricochet instance publishes ONE hidden service, which serves as its identity and accepts connections from contacts. With the prekey server it will publish two: one for its identity and one for the prekey server it uses... it will be hard to know to which ricochet instance identity this prekey server identity belongs to. This can work if the instance contact identity is already in recipient's persistent contact list and somehow the prekey server hidden service is attached to it.

We can also make the prekey server a channel inside of the connection: channels exist within a connection, although they are lost when the connection is lost.

What do you think @olabini ?

**Comment by olabini** [comment]
I'm not sure if I understand everything you said. My fundamental problem is that if Alice wants to send an offline message to Bob, Alice needs Bob's identity, which Alice has. Then, based on Bob's identity, Alice needs a way of finding the prekey server and identity/key where Bob's Prekey stuff can be found. 

Now, I'm realizing that Ricochet will not support offline messages (since you can't send messages to an offline hidden service and have the message arrive later. But this is still a question in my mind.

One obvious answer is that these kinds of network needs a central server that is the prekey server for the whole network - but that kinda defeats the idea of server less networks.

**Comment by claucece** [comment]
Yeah. In the case of ricochet you can't really have offline message unless a server is forced. 

> One obvious answer is that these kinds of network needs a central server that is the prekey server for the whole network - but that kinda defeats the idea of server less networks.

Mmmm... yes. I think that serveless networks will only work without any kind of central server..

**Comment by olabini** [comment]
Right. But that leaves the question of how a prekey server can be found.

**Comment by claucece** [comment]
Well, my thinking is: the only way we now have offline messages is by using a prekey server. If a network ideal and model is to be serverless, I think we cannot force them to use one. We use the server for offline messages and these networks more often don't want that...

**Comment by claucece** [comment]
@olabini , please, check

**Comment by olabini** [comment]
Yes, absolutely! We can't force them, and maybe serverless just means offline won't be a possible. But that leaves us with the deniability problem of never publishing Client Profiles.

**Comment by claucece** [comment]
Mmm...

> But that leaves us with the deniability problem of never publishing Client Profiles

I guess Client Profiles can be published somewhere else, like even in a tweet. I guess a server is not per se needed for this. A client may publish client profiles, also, to a server pool (similar to a keyserver pool, where PGP public keys can be published).

**Comment by claucece** [comment]
Ok... so I guess I'll put a recommendation on the OTRv4 spec of where to publish the client profiles if no untrusted server exists, and that if a network is server-less, offline messages might not be supported.
