### ISSUE TITLE
Consider sending each submissions of prekey messages/client and prekey profiles as its own its own physical network message

### ISSUE THREAD

**Issue by claucece** [otrv4/otrv4-prekey-server#13]

**Comment by claucece** [comment]
Can you clarify this @olabini ?

I guess this means that as a publisher you send a DAKE_3 + n prekey messages, and the network can send each prekey message one at the time.. is that so?

**Comment by olabini** [comment]
Yeah, something like that. Basically very very lightweight fragmentation. The way I think about it is that the N prekey messages will form a long long byte array. That array can be divided up however the client sees fit, into smaller network messages. The only thing the server needs to know is N, and then the actual data can flow, independent of how many actual network messages are used.
