### ISSUE TITLE
Add a ZKPK of the private keys associated with some public values

### ISSUE THREAD

**Issue by claucece** [otrv4/otrv4-prekey-server#20]
Specifically, we would need proofs for:
 - ClientProfile public key
 - ClientProfile DSA key
 - PrekeyProfile shared prekey
 - PrekeyMessage y
 - PrekeyMessage b

The only flow that needs to be changed is the publication message:

Once the server gets a publication message, it sends back challenge values for each one of the values we need. The client generates the challenges, sends them back, and the server returns success or failure.

We also need to remember that we need to tie the shared secret from the DAKE into the proofs.

We should ratchet the following MACs for these values.

**Comment by olabini** [comment]
Talking to Nik and Ian, it's clear that we only need to prove the shared prekey from the Prekey Profile, and the y and b from the Prekey Messages - the other values are proven by the signatures already.

We will use a batch proof rooted in randomness from the shared secret generated during the AKE. This will give us three proofs that can be sent alongside the publication message.

**Comment by olabini** [comment]
This has been added to the spec now.
