### ISSUE TITLE
Review other encoded messages

### ISSUE THREAD

**Issue by juniorz** [otrv4/otrv4-prekey-server#5]
Originally, there was 3 DAKE messages part of the protocol which were serialized and base64'd.

There was also 2 messages to differentiate which "authenticated action" you wanted to do in the server (Prekey publication and Storage information) which had messages IDs rather than message types. They would go in the body of a DAKE-3 message.

Finally there was the "Storage Status Message" which were the only other encoded message sent by the server to the client that were encoded. it probably should have had `message type` rather than `message ID`.

We need to review how "No Prekey-Messages on Storage Message", "Success Message" and "Failure Message" fit into thiscontext.

**Comment by claucece** [comment]
Sorry, I did not notice that there was a `message type` and a `message id`. I'll change that. Thanks for pointing that out. 

> They would go in the body of a DAKE-3 message.

Having a message with a `message type` inside of another is no problem. It happens the same at the last Non-Interactive Auth message from the OTRv4 protocol.

**Comment by juniorz** [comment]
Yeah, sorry. We were aware the name was confusing, but it was left behind until we finished the rough draft.

**Comment by juniorz** [comment]
aee2c09 is actually #5, not #6.
