### ISSUE TITLE
Check the attacks and put them on the spec

### ISSUE THREAD

**Issue by juniorz** [otrv4/otrv4-prekey-server#7]
Original TODO

> Check replay, key reused, attacker modifies prekey or format?

>- What if the server delivers all the prekey messages to an adversary
> - How does forward secrecy is compromised when the prekey server refuses to hand
  out prekey messages?

**Comment by juniorz** [comment]
Interestingly the OTRv4 spec does not have an attacks section so I don't understand what makes this spec special that needs one section about attacks. No that evaluating the attacks is not important, but it is not part of the spec.

**Comment by claucece** [comment]
> Interestingly the OTRv4 spec does not have an attacks section so I don't understand what makes this spec special that needs one section about attacks. No that evaluating the attacks is not important, but it is not part of the spec.

Yeah. I was not thinking of specifically having an attacks section but this can create inputs for the assumptions or maybe 'security' properties. It is true that the OTRv4 spec does not have a section, but it is stated which limitations it has.
