### ISSUE TITLE
Crate a definitions section

### ISSUE THREAD

**Issue by claucece** [otrv4/otrv4-prekey-server#9]
Create a definitions section where 'Publisher', 'Retriever', etc are defined.

Define Denial of Service in the context of OTRv4.

**Comment by olabini** [comment]
I think it would be great if we could be more specific about DoS in this context - it doesn't feel like the commit does that.

**Comment by claucece** [comment]
Mmm.. I think that maybe this was already "defined" when we say:

```
Note that the Prekey Server is untrusted and therefore can cause the communication between two
parties to fail. This can happen in several ways:

The Prekey Server is unavailable.
The Prekey Server refuses to hand out Prekey Ensembles.
The Prekey Server hands out incomplete Prekey Ensembles.
The Prekey Server hands out expired Prekey Ensembles.
The Prekey Server hands out Prekey Messages that have been already used.
The Prekey Server reports incorrect number of stored Prekey Messages.
```

or should it be more specific?

**Comment by claucece** [comment]
@olabini is it enough with that?

**Comment by olabini** [comment]
Not really. This only talks about DoS from the perspective of the Prekey Server, but I think we also need to mention it from the perspective of third parties.

**Comment by claucece** [comment]
Ah, ok.
